<?php

module_load_include('inc', 'yearmanager', 'db');


function responseeditor_menu()
{
  $items = array();
	$items['responseeditor'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Participant Info Editor', //page title
    'description' => 'Edits survey responses.',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('response_editor_form'), //put the name of the form here
    'access callback' => TRUE
  );
  
  return $items;
}

function response_editor_ajax_callback($form, $form_state)
{	
	error_log('ajax: ' . print_r($content, true));
	
	/*if (count($form['result']['#header']) == 0)
	{
		$form['result']['#header'] = array('first_name' => 'First Name', 'last_name' => 'Last Name', 'email' => 'Email');
	}*/
	  
	return $form['result'];
}

function getPersonData($isMentor, $id)
{
	list($mentorTableName, $studentTableName) = getParticipantTableNames(getYear());
	
	$tableName = ($isMentor) ? $mentorTableName : $studentTableName;
	
	$result = db_select($tableName, 'mmt')
        ->fields('mmt')
        ->condition('id', $id, '=')
        ->execute()
        ->fetchAll();
		
	foreach ($result as $row)
	{
		return $row;
	}
}

function searchParticipantsByName($name)
{
	list($mentorTableName, $studentTableName) = getParticipantTableNames(getYear());
	
	$and = db_and();
	$names = explode(' ', $name);
	
	foreach ($names as $namePart)
	{
		$or = db_or();
		$or->condition('first_name', '%' . $namePart . '%', 'like');
		$or->condition('last_name', '%' . $namePart . '%', 'like');
		$and->condition($or);
	}
	
	$result = db_select($mentorTableName, 'mmt')
        ->fields('mmt',array('id','first_name', 'last_name', 'email'))
        ->condition($and)
        ->execute()
        ->fetchAll();
		
	$results = array();
	foreach ($result as $row)
	{
		$results['M' . $row->id] = array('first_name' => $row->first_name,
		'last_name' => $row->last_name,
		'email' => $row->email);
	}
	
	$result2 = db_select($studentTableName, 'mmt')
        ->fields('mmt',array('id','first_name', 'last_name', 'email'))
        ->condition($or)
        ->execute()
        ->fetchAll();
		
	foreach ($result2 as $row)
	{
		$results['S' . $row->id] = array('first_name' => $row->first_name,
		'last_name' => $row->last_name,
		'email' => $row->email);
	}
	
	return $results;
}

function choose_person_ajax_callback($form, &$form_state)
{
	if (!empty($form_state['input']['first_name']))
	{
		updateEditBoxes($form, $form_state);
	}

	return $form['form_group'];
}

function response_editor_form_submit($form, &$form_state)
{
	$values = $form_state['values'];
	$nid = $values['id'];
	
	list($mentorTableName, $studentTableName) = getParticipantTableNames(getYear());
	$typeChar = $form_state['values']['person_type'];
	$tableName = ($typeChar === 'M') ? $mentorTableName : $studentTableName;
  
  error_log(print_r($values, TRUE));
  $num_deleted = db_delete($tableName)
  ->condition('id', $nid)
  ->execute();
  
  drupal_set_message('Participant removed.');
}

function edit_button_callback($form, &$form_state)
{
	list($mentorTableName, $studentTableName) = getParticipantTableNames(getYear());
	$typeChar = $form_state['values']['person_type'];
	$form_state['values']['blah'] = 'hi';
	
	error_log('type_char: ' . $typeChar);
	//drupal_set_message('<pre>' . print_r($form_state['values'], TRUE) . '</pre>');

	error_log('First Name: ' . $form_state['values']['first_name']);
	error_log('First Name: ' . $form['form_group']['first_name']['#value']);
	$tableName = ($typeChar === 'M') ? $mentorTableName : $studentTableName;
	
	$columns = $form_state['values']['columns'];
	$fields = array();
	foreach ($columns as $column)
	{
		if ($column === 'id' || $column === 'timestamp') { continue; }
		$fields[$column] = $form_state['values'][$column];
	}
	
	error_log("FIELDDUMP" . print_r($fields, true));
	
	$num_updated = db_update($tableName)
	  ->fields($fields)
	  ->condition('id', $form_state['values']['id'], '=')
	  ->execute();
	  
	show($form['form_group']['edit_result']);
	//return $form['form_group']['edit_result'];
	return '<div style="margin-top: 1em; background-color: #d7e0e7; padding: 0.5em;">Participant has been edited.</div>';
}

function createTextField($column, $defaultValue)
{
	$friendlyName = getFriendlyName($column);
	
	$isLong = $column === 'comments' || $column === 'hobbies_interests' || $column === 'cs_interests' || $column === 'availability_comments';
	
	$type = $isLong ? 'textarea' : 'textfield';
	return array(
		  '#type' => $type,
		  '#title' => t($friendlyName),
		  '#default_value' => t($defaultValue)
		);
}

function getFriendlyName($column)
{
	/*if ($column === 'first_name') { return 'First Name'; }
	if ($column === 'last_name') { return 'Last Name'; }
	if ($column === 'current_employer') { return 'Current Employer'; }
	
	return $column;*/
	if ($column === 'cs_interests') { return "CS Interests"; }
	if ($column === 'hobbies_interests') { return "Hobbies and Interests"; }
	return ucwords(str_replace('_', ' ', $column));
}

function response_editor_form($form, &$form_state)
{
	$form['searchName'] = array
	(
		'#type' => 'textfield',
		'#title' => t('Find a participant')
	);
	
	$form['go'] = array
	(
		'#type' => 'button',
		'#value' => 'Search',
		'#attributes' => array('class' => array('container-inline')), 
		'#ajax' => array(
			'callback' => 'response_editor_ajax_callback',
			'wrapper' => 'result_div',
			'effect' => 'fade',
			'event' => 'click'
		)
	);
	
	$form['spacer'] = array('#markup' => '<div style="clear:both;">&nbsp;</div>');
	
	$editing = array_key_exists('values', $form_state);
		
	if (array_key_exists('values', $form_state))
	{
		$content = searchParticipantsByName($form_state['values']['searchName']);
	}
	else
	{
		$content = array();
	}

	$form['result'] = array(
	  '#type' => 'tableselect',
	  '#header' => array(),
	  '#options' => $content,
	  '#prefix' => '<div id="result_div" style="float:left;margin-right: 2em;">',
	  '#suffix' => '</div>',
	  '#multiple' => false,
	  '#ajax' => array(
			'callback' => 'choose_person_ajax_callback',
			'wrapper' => 'group_div',
			'effect' => 'fade',
			'progress' => array('type' => 'throbber')
		)
	  );
	  
	$form['result']['#header'] = array('first_name' => 'First Name', 'last_name' => 'Last Name', 'email' => 'Email');
	  
	 $form['fieldsWrapper'] = array(
		'#markup' => '<div id="group_div"></div>'
	 );

	if ($editing)
	{
		createEditBoxes($form, $form_state);
	}
	
	return $form;
}

function getPersonDataById($personId)
{	
	$typeChar = substr($personId, 0, 1);
	$isMentor = $typeChar === 'M';
	$numId = substr($personId, 1);
		
	$personData = getPersonData($isMentor, $numId);
	return array($personData, $isMentor, $numId);
}

function updateEditBoxes(&$form, &$form_state)
{
	error_log("Update Edit Box: " . $form_state['values']['result']);
	list($personData, $isMentor, $numId) = getPersonDataById($form_state['values']['result']);
	$form_state['values']['person_type'] = ($isMentor) ? 'M' : 'S';
	$form_state['values']['id'] = $numId;
	$form['form_group']['#title'] = $isMentor ? 'Edit Fields (Mentor)' : 'Edit Fields';
	
	foreach ($personData as $column=>$value)
	{
		if ($column === 'id' || $column === 'timestamp') { continue; }
		unset($form_state['input'][$column]);
		unset($form['form_group'][$column]['#value']);
		unset($form['form_group'][$column]['#default_value']);
		error_log("Update Edit Box value: " . $value);
		$form['form_group'][$column]['#value'] = $value;
		$form['form_group'][$column]['#default_value'] = $value;
	}
}

function createEditBoxes(&$form, $form_state)
{
	list($personData, $isMentor, $numId) = getPersonDataById($form_state['values']['result']);
		
	$form['form_group'] = array(
		  '#type' => 'fieldset',
		  '#title' => t('Edit Fields'),
		  '#collapsible' => FALSE,
		  '#collapsed' => FALSE,
		  '#prefix' => '<div id="group_div">',
		  '#suffix' => '</div>'
		);
		
	$form['form_group']['#title'] = $isMentor ? 'Edit Fields (Mentor)' : 'Edit Fields';
		
	$form['form_group']['person_type'] = array(
		'#type' => 'hidden',
		'#value' => $isMentor ? 'M' : 'S'
	);
	$form['form_group']['id'] = array(
		'#type' => 'hidden',
		'#value' => $numId
	);
	$form['form_group']['columns'] = array(
		'#type' => 'hidden',
		'#value' => array_keys(get_object_vars($personData))
	);
	
	error_log('PD: ' . print_r($personData, true));
	error_log('PDK: ' . print_r(array_keys(get_object_vars($personData)), true));
	
	foreach ($personData as $column=>$value)
	{
		if ($column === 'id' || $column === 'timestamp') { continue; }
		error_log('value: ' . $value);
		$form['form_group'][$column] =
			createTextField($column, $value);
	}
	
	$form['form_group']['edit'] =
	array
	(
		'#type' => 'button',
		'#value' => t('Edit'),
		'#ajax' => array(
			'callback' => 'edit_button_callback',
			'wrapper' => 'edit_div'
		)
	);
	
	$form['form_group']['remove'] =
	array
	(
		'#type' => 'submit',
		'#value' => t('Remove Participant')
	);
	
	error_log("Edit" . $form_state['values']['edit']);
	//error_log("Blah" . print_r($form_state['values']['blah'], TRUE));
	error_log("Blah" . array_key_exists('blah', $form_state['values']));
	
	if (array_key_exists('blah', $form_state['values']))
	{
		error_log("blah2");
	}
	
	$form['form_group']['edit_result'] = array(
	  '#markup' => '',
	  '#prefix' => '<div id="edit_div" style="display: ' . (array_key_exists('blah', $form_state['values']) ? "block" : "none") .';">',
	  '#suffix' => '</div>'
	);
	
	//hide($form['form_group']['edit_result']);
	
}
