<?php

module_load_include('inc', 'matcherizer', 'matcherizer');

function matcherizer_menu() {
    $items = array();
    $items['matcherizer'] = array(
        'title'           => 'Matcherizer',
        'description'     => 'Set weightings to generate matches.',
        'page callback'   => 'drupal_get_form',
        'page arguments'  => array('matcherizer_form'),
        'access callback' => TRUE,
        );
    return $items;
}

function matcherizer_form($form, &$form_state) {
    $fields_to_match = getFieldsToMatch();

    foreach ($fields_to_match as $short_name => $visible_name) {
        $form[$short_name] = array(
            '#title' => t($visible_name),
            '#type' => 'textfield',
            '#required' => TRUE,
            );
    }

    $form['submit'] = array(
        '#value' => 'Submit',
        '#type' => 'submit',
        );
    return $form;
}

function check_valid_number($name, $short, &$values) {
    if (is_numeric($values[$short]) == False) {
        form_set_error($short, t($name.' weighting must be a number.'));
    }
    else if (!($values[$short] >= 0)) {
        form_set_error($short, t($name.' weighting must be non-negative.'));
    }
}

function matcherizer_form_validate($form, &$form_state) {
    $fields_to_match = getFieldsToMatch();
    foreach ($fields_to_match as $short_name => $visible_name) {
        check_valid_number($visible_name, $short_name, $form_state['values']);
    }
}

function matcherizer_form_submit($form, &$form_state) {
    // TODO get states from the database
    $states = array();

    $fields_to_match = getFieldsToMatch();
    foreach ($fields_to_match as $short_name => $visible_name) {
        $states[$short_name] = $form_state['values'][$short_name];
    }

    match(getYear(), $states);
}
