<?php
/*
module_load_include('php', 'matcherizer', 'matcherizer');

function matcherizer_menu() {
    $items = array();
    $items['matcherizer'] = array(
        'title' => 'Matcherizer',
        'description' => 'Set weightings to generate matches.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('matcherizer_form'),
        'access callback' => TRUE,
        );
    return $items;
}

function matcherizer_form($form, &$form_state) {
    // TODO Dynamically generate these based on question selection

    $form['gender_pref'] = array(
        '#title' => t('Gender Preference'),
        '#type' => 'textfield',
        '#required' => TRUE,
      );
    $form['cs_interests'] = array(
        '#title' => t('CS Interests'),
        '#type' => 'textfield',
        '#required' => TRUE,
      );
    $form['hobbies_interests'] = array(
        '#title' => t('Hobbies and Interests'),
        '#type' => 'textfield',
        '#required' => TRUE,
      );
    $form['submit'] = array(
        '#value' => 'Submit',
        '#type' => 'submit',
        );
    return $form;
}

function check_valid_number($name, $short, &$form_state) {
    if (is_numeric($form_state['values'][$short]) == False) {
        form_set_error($short, t($name.' weighting must be a number.'));
    }
    else if (!($form_state['values'][$short] >= 0)) {
        form_set_error($short, t($name.' weighting must be non-negative.'));
    }
}

function matcherizer_form_validate($form, &$form_state) {
    check_valid_number('Gender Preference', 'gender_pref', $form_state);
    check_valid_number('CS Interests', 'cs_interests', $form_state);
    check_valid_number('Hobbies and Interests', 'hobbies_interests', $form_state);
}

function matcherizer_form_submit($form, &$form_state) {
    // TODO get states from the database
    $states = array(
        'gender_pref' => $form_state['values']['gender_pref'],
        'cs_interests' => $form_state['values']['cs_interests'],
        'hobbies_interests' => $form_state['values']['hobbies_interests'],
        );

    match(getYear(), $states);
}
*/