<?php

module_load_include('inc', 'yearmanager', 'db');

function yearmanager_menu() {
    $items = array();
    $items['yearmanager'] = array(
        'title'           => 'Year Manager',
        'description'     => 'Select the current year and archive years.',
        'page callback'   => 'drupal_get_form',
        'page arguments'  => array('yearmanager_form'),
        'access callback' => TRUE,
        );
    return $items;
}

function yearmanager_form($form, &$form_state) {
    $all_years = getYearsInfo();
    
    $options = array();

    $default = 0;
    $index = 0;
    $hasNonArchived = FALSE;

    foreach ($all_years as $curr) {
        $ystr = $curr['year'];
        if ($curr['archived']) {
            $ystr = $ystr.' (Archived)';
        } else {
            $hasNonArchived = TRUE;
        }
        if ($curr['active']) {
            $ystr = $ystr.' (CURRENTLY MANAGING)';
            $default = $index;
        }
        ++$index;
        array_push($options, t($ystr));
    }

    if (!$hasNonArchived) {
        array_push($options, t('Create a new year'));
    }

    $form['current_year'] = array(
        '#title'         => t('Select a year.'),
        '#type'          => 'select',
        '#required'      => TRUE,
        '#options'       => $options,
        '#default_value' => $options[$default],
        );

    if (!$hasNonArchived) {
        $form['new_year'] = array(
            '#title'    => t('If you selected "Create a new year", enter the year in the form 2014-2015 in the box here.'),
            '#type'     => 'textfield',
            );
    } else {
        $form['set_archive'] = array(
            '#title'    => t('Check here to archive the selected year.'),
            '#type'     => 'checkbox',
            );
    }

    $form['set_active'] = array(
        '#title'    => t('Check here to choose the selected year as active.'),
        '#type'     => 'checkbox',
        );

    $form['submit'] = array(
        '#value' => 'Submit',
        '#type'  => 'submit',
        );
    return $form;
}

function yearmanager_form_validate($form, &$form_state) {
    if (array_key_exists('new_year', $form_state['values'])) {
        $new_year = $form_state['values']['new_year'];
        // check new year ahderes to format
        if ($new_year && !preg_match('/\d\d\d\d-\d\d\d\d/', $new_year)) {
            form_set_error('new_year', t('The new year is not in a valid format.'));
        }
    }
}

function yearmanager_form_submit($form, &$form_state) {
    $results = $form_state['values'];

    // Get selected year
    $selected_year = substr($form['current_year']['#options'][(int)$results['current_year']], 0, 9);

    if (array_key_exists('set_archive', $results)) {
        // Setting current year to archive
        $set_archive = $results['set_archive'];
        if ($set_archive) {
            setYearArchived($selected_year);
        }
    }

    if (array_key_exists('new_year', $results)) {
        // Create a new year
        $new_year = $results['new_year'];
        if ($new_year) {
            createNewYear($new_year);
            $selected_year = $new_year;
        }
    }

    if (array_key_exists('set_active', $results)) {
        // Set current year as active if different from current active year
        // Get current active year
        $set_active = $results['set_active'];
        if ($set_active) {
            $active_year = getYear();
            if ($selected_year != $active_year) {
                setYearActive($active_year, FALSE);
                setYearActive($selected_year, TRUE);
            }
        }
    }
}
