<?php

module_load_include('inc', 'yearmanager', 'db');

function yearmanager_menu() {
    $items = array();
    $items['yearmanager'] = array(
        'title'           => 'Year Manager',
        'description'     => 'Select the current year and archive years.',
        'page callback'   => 'drupal_get_form',
        'page arguments'  => array('yearmanager_form'),
        'access callback' => TRUE,
        );
    return $items;
}

function yearmanager_form($form, &$form_state) {
    $all_years = getYearsInfo();
    
    $options = array();

    $default = 0;
    $index = 0;
    $hasNonArchived = FALSE;

    foreach ($all_years as $curr) {
        $ystr = $curr['year'];
        if ($curr['archived']) {
            $ystr = $ystr.' (Archived)';
        } else {
            $hasNonArchived = TRUE;
        }
        if ($curr['active']) {
            $ystr = $ystr.' (CURRENTLY MANAGING)';
            $default = $index;
        }
        ++$index;
        array_push($options, t($ystr));
    }

    if (!$hasNonArchived) {
        array_push($options, t('Create a new year'));
    }

    $form['current_year'] = array(
        '#title'         => t('Select year to manage.'),
        '#type'          => 'select',
        '#required'      => TRUE,
        '#options'       => $options,
        '#default_value' => $options[$default],
        );

    if (!$hasNonArchived) {
        $form['new_year'] = array(
            '#title'    => t('If you selected "Create a new year", enter the year in the form 2014-2015 in the box here.'),
            '#type'     => 'textfield',
            );
    } else {
        $form['set_archive'] = array(
            '#title'    => t('Check here to archive the selected year above.'),
            '#type'     => 'checkbox',
            );
    }

    $form['submit'] = array(
        '#value' => 'Submit',
        '#type'  => 'submit',
        );
    return $form;
}

function yearmanager_form_validate($form, &$form_state) {
}

function yearmanager_form_submit($form, &$form_state) {
    $results = $form_state['values'];
    dpm($results);
}
