<?php

//include_once DRUPAL_ROOT . '/includes/database/database.inc';
module_load_include('inc', 'yearmanager', 'db');
module_load_include('inc', 'kickoff', 'kickoff');
module_load_include('inc', 'kickoff', 'debug');

$GLOBALS['MAX_GROUP_SIZE'] = 9;

function getPersonFromDbRow($record)
{
	return array("name" => $record->first_name, "prefs" => ["year" => 1, "hobbies" => explode(',', $record->hobbies_interests)]);
}

function getPersonInfoFromDb($id, $tableName)
{
	
	//$tablePart = '';
	//if ($mentor) { $tablePart = 'mentor'; } else { $tablePart = 'student'; }
	
	$result = db_query("SELECT * FROM " . $tableName ." WHERE id = :id", array(':id' => $id));
	
	foreach ($result as $record)
	{	
		return getPersonFromDbRow($record);
	}
}

function countAvailability($availabilities)
{
	$count = 0;
	foreach ($availabilities as $year => $availability) {if ($availability == 1) { ++$count; } }
	return $count;
}

function getTrioBuckets()
{
	$currentYear = getYear();

	$result = db_select('maestro_matched_trios', 'mmt')
        ->fields('mmt')
        ->condition('mentoring_year', $currentYear, '=')
        ->execute()
        ->fetchAll();
		
	#echo $currentYear;
	list($mentor_table_name, $student_table_name) = getParticipantTableNames($currentYear);
// Result is returned as a iterable object that returns a stdClass object on each iteration
	$jsonTrios = null;
	$jsonResult = null;
	
	$people = array();
	
	# Classify trios depending on how many nights they are available on.
	$trioBuckets = array();
	$allNights = null;
	
	foreach ($result as $record)
	{
		$data = $record->trios;
		$jsonResult = json_decode($data, true);
		
		$trioId = 0;
		foreach ($jsonResult as $trio)
		{
			$availability = $trio['kickoff'];
			if ($allNights == null) { $allNights = $availability; }
			$numNightsAvailable = countAvailability($availability);
			$trio['id'] = $trioId;
			if (!array_key_exists($numNightsAvailable, $trioBuckets))
			{
				$trioBuckets[$numNightsAvailable] = array();
			}
			array_push($trioBuckets[$numNightsAvailable], $trio);
			//echo $numNightsAvailable;
			
			$trioId++;
		}
		break;
	}
	
	return array($allNights, $trioBuckets);
}

function kickoff_menu()
{
  $items = array();
  

$items['kickoff'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Kickoff Night Group Generator', //page title
    'description' => 'Generates kickoff night groups.',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('kickoff_form'), //put the name of the form here
    'access callback' => TRUE
  );
  
  return $items;
}

function distributeBucketsIntoNights($allNights, $buckets)
{
	$returnNights = array();
	ksort($buckets);
	
	foreach ($allNights as $night=>$value)
	{
		$returnNights[$night] = array();
	}
	
	foreach ($buckets as $nightsAvailable => $trios)
	{
		if ($nightsAvailable === 1)
		{
			foreach ($trios as $trio)
			{
				$nightAvailable = null;
				foreach ($trio['kickoff'] as $night=>$available)
				{
					if ($available === 1) { $nightAvailable = $night; break; }
				}
				array_push($returnNights[$nightAvailable], $trio);
			}
		}
		else
		{
			foreach ($trios as $trio)
			{
				$nightsAvailable = array();
				foreach ($trio['kickoff'] as $night=>$available)
				{
					if ($available === 1) { $nightsAvailable[$night] = count($returnNights[$night]); }
				}
				
				asort($nightsAvailable);
				reset($nightsAvailable);
				$nightWithFewestTrios = key($nightsAvailable);
				array_push($returnNights[$nightWithFewestTrios], $trio);
			}
			
		}
	}
	
	return $returnNights;
}

function flattenTrios($trios)
{
	$titles = array('mentor','senior','junior');
	$people = array();
	list($mentorTableName, $studentTableName) = getParticipantTableNames(getYear());
	
	foreach ($trios as $trio)
	{
		$x = 0;
		foreach ($titles as $title)
		{
			$keyId = intval($trio[$title]);
			if ($x++ == 0) { $personInfo = getPersonInfoFromDb($keyId, $mentorTableName);
			} else { $personInfo = getPersonInfoFromDb($keyId, $studentTableName); }
			
			$personInfo['trio'] = $trio['id'];
			$personInfo['title'] = $title;
			array_push($people, $personInfo);
		}
		
	}
	
	return $people;
}

function outputAllGroups($allGroups)
{
	$html = '';
	foreach ($allGroups as $night=>$groups)
	{
		$temp = '<div style="float: left; padding-right: 2em;"><h2>Groups for Night ' . $night . '</h2>';
		$temp .= outputGroups($groups);
		$temp .= '</div>';
		$html .= $temp;
	}
	$html .= '<div style="clear: both;">&nbsp;</div>';
	return $html;
}

function kickoff_form($form, &$form_state)
{
	//$people = get_data();
	/* $people = array(
	array("name" => "Bill", "trio" => 4, "nights" => [0=>true], "prefs" => ["year" => 1, "hobbies" => ["sports","art"]])
	,array("name" => "Eric", "trio" => 1, "nights" => [2=>true], "prefs" => ["year" => 3, "hobbies" => ["sports","music"]])
	,array("name" => "Ted", "trio" => 3, "nights" => [3=>true], "prefs" => ["year" => 2, "hobbies" => ["fishing","cooking"]])
	,array("name" => "Alvin", "trio" => 2, "nights" => [4=>true], "prefs" => ["year" => 6, "hobbies" => ["sports","art"]])
	//,array("name" => "Alvin2", "prefs" => ["year" => 0])
	//,array("name" => "Alvin3", "prefs" => ["year" => 0])
	);*/
	#echo(count($people) . ' people total. <br />');
	#printGroups(kickoff(1,$people));
	list($allNights, $buckets) = getTrioBuckets();
	//printTrioBuckets($buckets);
	$nights = distributeBucketsIntoNights($allNights, $buckets);
	//printNights($nights);
	
	$allGroups = array();
	foreach ($nights as $night=>$trios)
	{
		$people = flattenTrios($trios);
		$groups = kickoff($night,$people);
		//$fixedGroups = fixGroups($groups);
		$allGroups[$night] = $groups;
	}
  
	$form['some_text'] = array(
	  '#markup' =>
	  count($people) . ' people total. <br />' . outputAllGroups($allGroups)
	  );

	$form['name'] = array(
	'#type' => 'textfield', //you can find a list of available types in the form api
	'#title' => "What is Your Name?",
	'#size' => 10,
	'#maxlength' => 10,
	'#required' => TRUE, //make this field required 
	);

	$form['price'] = array(
	'#type' => 'textfield', //you can find a list of available types in the form api
	'#title' => 'What is Your Price?',
	'#size' => 10,
	'#maxlength' => 10,
	'#required' => TRUE, //make this field required 
	);

	$form['submit_button'] = array(
	'#type' => 'submit',
	'#value' => t('Click Here!'),
	);

	return $form;
}

function kickoff_form_validate($form, &$form_state)
{
	if (!($form_state['values']['price'] > 0))
	{
		form_set_error('price', t('Price must be a positive number.'));
	}
}

function kickoff_form_submit($form, &$form_state)
{
	$values = $form_state['values'];
	db_insert('dbtng_example')
	->fields(array('name' => $values['name'], 'price' => $values['price']))
	->execute();
}
